name: Deploy SavoryAI App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Composer dependencies (for build)
        run: composer install --no-dev --optimize-autoloader

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install NPM dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Prepare deployment files
        run: |
          # Copy environment file
          if [ -f .env.production ]; then
            cp .env.production .env
          else
            cp .env.example .env
          fi

          # Create deployment info
          echo "Deployed at: $(date)" > deployment-info.txt
          echo "Commit: ${{ github.sha }}" >> deployment-info.txt

      - name: Deploy to hosting via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/vendor/**
            **/node_modules/**
            **/tests/**
            **/storage/logs/**
            **/storage/framework/cache/**
            **/storage/framework/sessions/**
            **/storage/framework/views/**
            **/.env.example
            **/phpunit.xml
            **/package*.json
            **/tailwind.config.js
            **/vite.config.js
            **/postcss.config.js
            **/.editorconfig
            **/README.md
            **/scripts/**
            **/.github/**

      - name: Deployment notification
        run: |
          echo "✅ Deployment completed successfully!"
          echo "📋 Manual steps required on hosting:"
          echo "1. Run: composer install --no-dev --optimize-autoloader"
          echo "2. Run post-deploy.php script for cache optimization"
          echo "3. Check .env file configuration"
